// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZY7GqSM4JFc8MQ-dNVjpvLEJnktUyEHU',
    appId: '1:473785623745:web:b6e7cca4d374d341f76040',
    messagingSenderId: '473785623745',
    projectId: 'brew-crew-e1e6c',
    authDomain: 'brew-crew-e1e6c.firebaseapp.com',
    storageBucket: 'brew-crew-e1e6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpZgzmgQtDiTXOayQFz7CGmAvzn0aYN30',
    appId: '1:473785623745:android:0e727d0e0b850d88f76040',
    messagingSenderId: '473785623745',
    projectId: 'brew-crew-e1e6c',
    storageBucket: 'brew-crew-e1e6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKsCmd9uhXYRF-oIpWhMu-RqZB79IQnQ',
    appId: '1:473785623745:ios:6b8d9ea5f758c7d0f76040',
    messagingSenderId: '473785623745',
    projectId: 'brew-crew-e1e6c',
    storageBucket: 'brew-crew-e1e6c.appspot.com',
    iosBundleId: 'com.example.brewcrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfKsCmd9uhXYRF-oIpWhMu-RqZB79IQnQ',
    appId: '1:473785623745:ios:82a98c32f1f72722f76040',
    messagingSenderId: '473785623745',
    projectId: 'brew-crew-e1e6c',
    storageBucket: 'brew-crew-e1e6c.appspot.com',
    iosBundleId: 'com.example.brewcrew.RunnerTests',
  );
}
